gxqpt:
  port:
    nginx: 10086
    eureka: 10030
    gate: ${gxqpt.port.nginx}   # 测试环境使用nginx
  hostname:
    redis: 192.168.0.53     # 根据环境更改
    rabbitmq: 192.168.0.53   # 根据环境更改
    mysql: 192.168.0.53       # 根据环境更改
    nginx: 127.0.0.1      # 测试不走nginx 就填写本机
    eureka: 192.168.0.191    # 根据环境更改
    gate: ${gxqpt.hostname.nginx}     # 测试环境使用nginx
    auth: 192.168.0.191
  mysql:
    admin:
      database: gxqpt_core_test       # 根据环境更改
    port: 3218                  # 根据环境更改
    username: root              # 根据环境更改
    password: LLm65c0VVd3axid9u+Y7DZeKwcODMjU95FRhxom6ApE2yZ1kbi5YzSsdAIz+edUOZH3Engm17+NyfyNczpaYlw==

spring:
  profiles:
    active: test2
  redis:
    host: ${gxqpt.hostname.redis}
    port: 16379
    pool:
      max-active: 10
      min-idle: 1
      max-idle: 4
      max-wait: 100
    key-prefix: test
    password: SbtyMveYNfLzTks7H0apCmyStPzWJqjy
  rabbitmq:
    port: 5672
    username: gxqpt
    password: gxqpt

eureka:
  client:
    serviceUrl:
      defaultZone: http://${gxqpt.hostname.eureka}:${gxqpt.port.eureka}${gxqpt.context-path.eureka}/eureka/

id-generator:
  machine-code: 1  # id生成器机器掩码
